--- #YAML:1.0
name:                Geo-Hashing
version:             0.01
abstract:            Perl library to calculate Geohashing points
license:             ~
author:              
    - Dan Boger <zigdon@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest::MD5:                   0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
